version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - file_handler

  file_handler:
    build:
      context: ./file_handler
      dockerfile: Dockerfile
    ports:
      - "8001:8001"