version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - prepared_data

  prepared_data:
    build:
      context: prepared_data_
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  predicted_data:
    build:
      context: predicted_data_
      dockerfile: Dockerfile
    ports:
      - "8002:8002"