parser: "Demo"
logical_cores: 100
relative_data_path: 'data/data.csv'
target_variables: []
number_of_x_columns: 14
number_of_y_columns: 1
random_seed: 42
test_size: 0.2
lower_quantile: 0.25
upper_quantile: 0.75
degree: 3